---
- name: Deploy Artifact to Localhost
  hosts: localhost
  tasks:
    - name: Copy the artifact to Downloads folder
      copy:
        src: "/var/lib/jenkins/workspace/akash/target/sindhu-1.0-SNAPSHOT.jar"
        dest: "/home/jenkins/Downloads/t.jar"
